cronjob:
  crons:
    - name: "one"
      schedule: "0 0 * * 0"
      suspend: true

concurrencyPolicy: Replace

image:
  repository: registry.happytravel.com/juniper-connector-updater
  imagePullSecrets: travel-registry
  restartPolicy: Never
  pullPolicy: Always
  tag: latest

resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
     cpu: 100m
     memory: 512Mi

env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Staging" 
  HTDC_VAULT_ENDPOINT: "http://vault.staging.svc.k8s.dev:8200/v1/"
  HTDC_REDIS_HOST: "redis-jc"
  CONSUL_HTTP_ADDR: "http://consul-consul-server.staging.svc.k8s.dev:8500/"
